### ISSUE TITLE
IOS100 - Slide 12

### ISSUE THREAD

**Issue by ricardoalcocer** [appcelerator-training/learning-paths#1]
@tzmartin There's a rendering problem with the bullets being forced into a second column.  It also happens in full screen mode.

![](http://sht.tl/7woGlL)

**Comment by tzmartin** [comment]
Try breaking up the list item into two sections like this..

```
- ActivityIndicator
- Button
- ImageView
- Label
- ProgressBar
- SearchBar


- Slider
- Switch
- TableView
- TextArea
- TextField
- WebView
```

The renderer will break layout into 2 columns..

**Comment by tzmartin** [comment]
Put two line breaks to separate into two columns

![](https://monosnap.com/file/LWLhDEbcQhtxgAkfWUcorhynHnHjsL.png)

**Comment by ricardoalcocer** [comment]
Ok.  I'll leave it to you so I don't collide with what you're working on.

**Comment by ricardoalcocer** [comment]
closing
